language: node_js
node_js:
  - "7.8"
sudo: required

services:
  - docker
  
install:
  - echo "nothing to install"

script:
  - echo "none"
  
after_sucess:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t hwd .
  - docker tag hwd:latest 511553801008.dkr.ecr.us-east-1.amazonaws.com/hwd:latest
  - docker push 511553801008.dkr.ecr.us-east-1.amazonaws.com/hwd:latest
  
