version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t hwdtest .
      - docker tag hwdtest:latest 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:latest
