version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-west-2)
      - REPOSITORY=511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest
      - TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t $REPOSITORY:latest .
      - docker tag $REPOSITORY:latest $REPOSITORY:$TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY:latest
      - docker push $REPOSITORY:$TAG
      - echo Writing container definitions file...
      - printf '[{"name":"tecontainer","imageUri":"%s"}]' $REPOSITORY:$TAG > containerdefinitions.json
artifacts:
    files: containerdefinitions.json
