version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-west-2)
      - REPOSITORY_URI=511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest
      - TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:latest .
      - docker tag 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:latest 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:$TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:latest
      - docker push 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:$TAG
      - echo Writing image definitions file...
      - printf '[{"name":"hellocdcontainer","imageUri":"%s"}]' 511553801008.dkr.ecr.us-west-2.amazonaws.com/hwdtest:$TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
