Parameters:
  Tag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number
    Default: 1

Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: devcluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
   
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: testtaskdef
      ContainerDefinitions:
        - Name: testcontainer
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hwdtest:${Tag}
          Essential: true
          Memory: 128
          PortMappings:
            - ContainerPort: 8080
              HostPort: 80
          Environment:
            - Name: Tag
              Value: !Ref Tag
